### ISSUE TITLE
Could you explain how the firefox/chrome plugins can be installed.

### ISSUE THREAD

**Issue by HodeiG** [dodying/Bookmark-Sync#1]
Ho dodying,

I was looking for a method to sync my bookmarks between firefox/chrome using gist to store the bookmarks. I believe that's what your project does. However, could you explain in your README file how to install these plugins in the browsers (in the meantime I will google it). In general, if you could update your README file to explain how to setup everything would be very nice.

Many thanks,

**Comment by dodying** [comment]
i uploaded the file here
[https://github.com/dodying/Bookmark-Sync/releases/latest](https://github.com/dodying/Bookmark-Sync/releases/latest)

note: backup before `Download`/`History`/`Sync`

recommend test on browser with new profile
